local m=dofile('/usr/share/campus-guard/metrics.lua')
local function sample(t,flow,minutes,id)
  return {epoch=t,flow_kib=flow,time_minutes=minutes,identity=id or 'test-account',authenticated=true}
end
local start=os.time({year=2026,month=10,day=7,hour=23,min=59,sec=30})
local s=m.update(nil,sample(start,10000,120))
assert(s.hours[1].bytes==0 and s.hours[1].coverage_seconds==0,'baseline must not backfill lifetime usage')
s=m.update(s,sample(start+60,10100,122))
assert(#s.hours==2,'midnight split')
assert(s.hours[1].bytes==51200 and s.hours[2].bytes==51200,'bytes conserved across midnight')
assert(s.hours[1].minutes==1 and s.hours[2].minutes==1,'minutes conserved across midnight')
assert(s.hours[1].coverage_seconds==30 and s.hours[2].coverage_seconds==30,'coverage split')
local v=m.view(s,'2026-10-08')
assert(#v.hourly==24 and v.hourly[1].bytes==51200,'hourly series')
assert(#v.daily==2 and v.daily[1].bytes+v.daily[2].bytes==102400,'daily reconciles hourly')
assert(v.baseline==nil and v.latest.identity==nil,'identity excluded from public view')
local json=require 'luci.jsonc'
local encoded=json.parse(json.stringify(v))
assert(encoded.daily[1]~=nil and encoded.daily[2]~=nil,'JSON serialization retains daily records')
assert(v.today_usage==nil or encoded.today_usage~=nil,'JSON serialization retains today summary')
s=m.update(s,sample(start+120,0,0))
assert(s.resets==1,'counter reset marked')
assert(s.hours[1].bytes+s.hours[2].bytes==102400,'reset does not invent usage')
s=m.update(s,sample(start+180,20,1))
assert(s.hours[1].bytes+s.hours[2].bytes==122880,'increments resume after reset')
s=m.update(s,sample(start+480,100,6))
assert(s.gaps==1 and s.unassigned_bytes==81920 and s.unassigned_minutes==5,'long gap not assigned to invented hours')
s=m.update(s,sample(start+540,1000,7,'other-account'))
assert(s.resets==2,'identity change establishes new baseline')
local before=s.hours[1].bytes+s.hours[2].bytes
s=m.update(s,{epoch=start+600,authenticated=false})
assert(s.hours[1].bytes+s.hours[2].bytes==before,'offline sample not counted as usage')
s=m.update(s,{epoch=start+660,authenticated=true,identity='other-account',flow_kib=4294967295,time_minutes=4294967295})
assert(s.hours[1].bytes+s.hours[2].bytes==before,'sentinel values ignored')
local zero=m.update(nil,sample(start,100,1))
zero=m.update(zero,sample(start+60,100,1))
assert(zero.hours[1].bytes==0 and zero.hours[1].coverage_seconds>0,'observed zero distinct from missing')
local future=start+91*86400
zero=m.update(zero,sample(future,100,1))
for _,h in ipairs(zero.hours) do assert(h.epoch>=math.floor(future/3600)*3600-90*86400,'retention enforced') end
print('Metrics tests PASS: baseline, midnight conservation, public privacy, resets, long gaps, account changes, offline, sentinels, zero vs missing, retention')
